apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-backend
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-backend
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: ai-interviewer-backend
    app.kubernetes.io/component: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP