apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-loadbalancer
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-loadbalancer
    app.kubernetes.io/component: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ai-interviewer-nginx-gateway
    app.kubernetes.io/component: gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP