apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interviewer-nginx-gateway
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-nginx-gateway
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-interviewer-nginx-gateway
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-interviewer-nginx-gateway
        app.kubernetes.io/component: gateway
    spec:
      containers:
      - name: nginx-gateway
        image: ai-interviewer/nginx-gateway:latest
        imagePullPolicy: Never  # Use local minikube images
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: DEV_MODE
          value: "false"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-oauth-keys
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-oauth-keys
              key: GOOGLE_CLIENT_SECRET
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-nginx-gateway
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-nginx-gateway
    app.kubernetes.io/component: gateway
spec:
  selector:
    app.kubernetes.io/name: ai-interviewer-nginx-gateway
    app.kubernetes.io/component: gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP