apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-interviewer-grafana-pvc
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-grafana
    app.kubernetes.io/component: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard