apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-grafana
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-grafana
    app.kubernetes.io/component: observability
spec:
  selector:
    app.kubernetes.io/name: ai-interviewer-grafana
    app.kubernetes.io/component: observability
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP