apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interviewer-grafana
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-grafana
    app.kubernetes.io/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-interviewer-grafana
      app.kubernetes.io/component: observability
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-interviewer-grafana
        app.kubernetes.io/component: observability
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.4.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "traceqlEditor"
        - name: GF_DEFAULT_PREFERENCES_HOME_DASHBOARD_UID
          value: "mcp-mesh-overview"
        - name: GF_USERS_HOME_PAGE
          value: "/d/mcp-mesh-overview/mcp-mesh-overview"
        - name: GF_USERS_DEFAULT_THEME
          value: "dark"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        - name: GF_ANALYTICS_REPORTING_ENABLED
          value: "false"
        - name: GF_NEWS_NEWS_FEED_ENABLED
          value: "false"
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboard
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-data
          mountPath: /var/lib/grafana
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: grafana-config
        configMap:
          name: ai-interviewer-grafana-config
      - name: grafana-datasources
        configMap:
          name: ai-interviewer-grafana-datasources
      - name: grafana-dashboards-config
        configMap:
          name: ai-interviewer-grafana-dashboards-config
      - name: grafana-dashboard
        configMap:
          name: ai-interviewer-grafana-dashboard
      - name: grafana-data
        persistentVolumeClaim:
          claimName: ai-interviewer-grafana-pvc