apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-interviewer-grafana-datasources
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-grafana
    app.kubernetes.io/component: observability
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://ai-interviewer-tempo:3200
        uid: tempo
        isDefault: true
        jsonData:
          nodeGraph:
            enabled: true
          tracesToLogsV2:
            datasourceUid: "loki"
            tags: ["job", "instance", "pod", "namespace"]
            mappedTags:
              - key: "service.name"
                value: "service"
            mapTagNamesEnabled: false
            spanStartTimeShift: "1h"
            spanEndTimeShift: "-1h"
            filterByTraceID: false
            filterBySpanID: false
          lokiSearch:
            datasourceUid: "loki"
          serviceMap:
            datasourceUid: "prometheus"