apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-interviewer-tempo-config
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-tempo
    app.kubernetes.io/component: observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: kubernetes
      storage:
        path: /var/tempo/generator/wal

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
      trace_by_id:
        duration_slo: 5s

    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics]