apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-tempo
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-tempo
    app.kubernetes.io/component: observability
spec:
  selector:
    app.kubernetes.io/name: ai-interviewer-tempo
    app.kubernetes.io/component: observability
  ports:
  - name: http
    port: 3200
    targetPort: 3200
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: 9095
    protocol: TCP
  type: ClusterIP