apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-interviewer-tempo-pvc
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-tempo
    app.kubernetes.io/component: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard