apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interviewer-tempo
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-tempo
    app.kubernetes.io/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-interviewer-tempo
      app.kubernetes.io/component: observability
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-interviewer-tempo
        app.kubernetes.io/component: observability
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.8.1
        args:
        - -config.file=/etc/tempo.yaml
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo.yaml
          subPath: tempo.yaml
        - name: tempo-data
          mountPath: /var/tempo
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: tempo-config
        configMap:
          name: ai-interviewer-tempo-config
      - name: tempo-data
        persistentVolumeClaim:
          claimName: ai-interviewer-tempo-pvc