apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interviewer-nginx-gateway
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-nginx-gateway
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-interviewer-nginx-gateway
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-interviewer-nginx-gateway
        app.kubernetes.io/component: gateway
    spec:
      containers:
      - name: nginx-gateway
        image: busybox:latest
        command: ['sh', '-c', 'echo "LoadBalancer Test - OK" > /tmp/index.html && while true; do { echo -e "HTTP/1.1 200 OK\r\nContent-Length: 22\r\n\r\nLoadBalancer Test - OK"; } | nc -l -p 80; done']
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"