apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-registry
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-registry
    app.kubernetes.io/component: registry
spec:
  selector:
    app.kubernetes.io/name: ai-interviewer-registry
    app.kubernetes.io/component: registry
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP