apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interviewer-nginx-gateway
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-nginx-gateway
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-interviewer-nginx-gateway
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-interviewer-nginx-gateway
        app.kubernetes.io/component: gateway
    spec:
      containers:
      - name: nginx-gateway
        image: ai-interviewer/nginx-gateway:latest
        imagePullPolicy: Never  # Use local minikube images
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: DEV_MODE
          value: "false"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-oauth-keys
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-oauth-keys
              key: GOOGLE_CLIENT_SECRET
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-oauth-keys
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-oauth-keys
              key: GITHUB_CLIENT_SECRET
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx-k8s.conf
        - name: nginx-lua
          mountPath: /etc/nginx/lua
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-simple-config
      - name: nginx-lua
        configMap:
          name: nginx-lua-scripts