apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-minio
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-minio
    app.kubernetes.io/component: storage
spec:
  selector:
    app.kubernetes.io/name: ai-interviewer-minio
    app.kubernetes.io/component: storage
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  type: ClusterIP