apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-interviewer-minio-init-script
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-minio
    app.kubernetes.io/component: storage
data:
  minio-init.sh: |
    #!/bin/bash
    # MinIO initialization script to set up bucket policies for internal access
    
    # Wait for MinIO to be ready
    echo "Waiting for MinIO to be ready..."
    sleep 10
    
    # Configure MinIO client
    echo "Configuring MinIO client..."
    mc alias set myminio http://ai-interviewer-minio:9000 minioadmin minioadmin123
    
    # Create bucket if it doesn't exist
    echo "Creating bucket ai-interviewer-uploads..."
    mc mb myminio/ai-interviewer-uploads --ignore-existing
    
    # Set bucket policy to allow anonymous read access for the entire bucket
    echo "Setting bucket policy for anonymous download access..."
    mc anonymous set download myminio/ai-interviewer-uploads
    
    echo "MinIO bucket ai-interviewer-uploads configured for anonymous download access"