apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-interviewer-minio-pvc
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-minio
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard