apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-interviewer-redis-pvc
  namespace: ai-interviewer
  labels:
    app.kubernetes.io/name: ai-interviewer-redis
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard